### ISSUE TITLE
unable to install cx-moltenvk checksum mismatch error

### ISSUE THREAD

**Issue by nsklaus** [Gcenx/macports-wine#14]
i installed macport, ran it through rosetta term, added your macport overlay, ran port install wine-staging.
all ran well, i now have wine 6.11. i tried to run a game, and was told:
`dx11 feature level 10.0 is required to run the engine.`
i thought i just needed to install cx-moltenvk, so i did: `sudo port install cx-moltenvk` and ran into a checksum mismatch error. here's below the steps i tried to install cx-moltenvk:

```
[ macports-wine ] 
$ sudo port search CX-MoltenVK
Password:
CX-MoltenVK @1.1.3_1 (graphics)
    an implementation of Vulkan for Metal
[ macports-wine ] 
$ sudo port install CX-MoltenVK
--->  Computing dependencies for CX-MoltenVK
Error: Can't install CX-MoltenVK because conflicting ports are active: MoltenVK
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port CX-MoltenVK failed
[ macports-wine ] 
$ sudo port uninstall moltenVK 
Note: It is not recommended to uninstall/deactivate a port that has dependents as it breaks the dependents.
The following ports will break: wine-staging @6.11_0
Continue? [y/N]: y
Warning: Uninstall forced.  Proceeding despite dependencies.
--->  Deactivating MoltenVK @1.1.3_0
--->  Cleaning MoltenVK
--->  Uninstalling MoltenVK @1.1.3_0
--->  Cleaning MoltenVK
[ macports-wine ] 
$ sudo port install CX-MoltenVK
--->  Computing dependencies for CX-MoltenVK
--->  Fetching distfiles for CX-MoltenVK
--->  Attempting to fetch macos_dxvk_patched.tar.xz from https://distfiles.macports.org/MoltenVK1.1.0_1
--->  Attempting to fetch macos_dxvk_patched.tar.xz from https://github.com/Gcenx/MoltenVK/releases/download/v1.1.0
--->  Verifying checksums for CX-MoltenVK                                            
Error: Checksum (rmd160) mismatch for macos_dxvk_patched.tar.xz
Error: Checksum (sha256) mismatch for macos_dxvk_patched.tar.xz
Error: Checksum (size) mismatch for macos_dxvk_patched.tar.xz
Error: Failed to checksum CX-MoltenVK: Unable to verify file checksums
Error: See /opt/local/var/macports/logs/_Users_klaus_Sources_macports-wine_graphics_MoltenVK/CX-MoltenVK/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port CX-MoltenVK failed
[ macports-wine ] 
$
```

------
update: i had my own compiled libMoltenVK.dylib, with the modification for dxvk, i use this lib with wineskin and crossover, it works as expected. so i tried to copy it in place of the packaged one like so:
```
sudo cp ~/Sources/MoltenVK/Package/Release/MoltenVK/dylib/macOS/libMoltenVK.dylib /opt/local/lib/
```
that worked, game now starts instead on showing error popup. but the general result is not on par with wineskin or crossover, for example, with fallout4, the game start, i see menu screen, (background image missing) i see the menu, i select load game, and it seems to be stuck in load forever. so even when everything is compiled and installed properly, something is still misbehaving somewhere in the stack. 

- fallout4 : won't run correctly (cannot go further than load screen)
- fallout new vegas: won't start at all
- witcher3 : seems to work fine though
- resident evil2 : installer won't run

**Comment by Gcenx** [comment]
I won’t get around to verifying the checksum for CX-MoltenVK for Apple Silicon until to tonight at the earliest. The version override will be removed after MoltenVK 1.1.4 lands as Witcher3 no longer crashes when hit last I checked. If you want to open a PR or just provide the new checksum from the log I can update it now.

- Fallout New Vegas; is a 32Bit title so won’t work with upstream wine.
- resident evil2; the original version is 32Bit

As for the others, no clue what the issue could be since it’s hard to compare WineCX20.0.2 (wine-5.0 with patches) to Wine-6.11.

**Comment by nsklaus** [comment]
i would have no clue on how to make a PR with what you requested, to correct the checksum error.
i'm not in a hurry however, i just wanted to report my findings.

i waited a few months, then tried plain wine again. it's coming along, step by step i see. now default driver display correctly, whereas before it was blank windows. wineskin too runs fine now. 

but, the major problem is still somewhat slow dx9, and for dx10 & 11 then it's moltenvk problems, missing extensions and rendering glitches.  i'm compiling moltenvk from trunk every now and then, my last build is from 3-4 days ago.
unfortunately i see only small improvements. i could confirm witcher3 no longer crash in fights, with latest moltenvk, which is nice. maybe when crossover 21 comes out, more improvement could come again on that front?
would you have any plan to make a wine6 based engine for wineskin ? 
are we waiting for crossover21 beta release for that process to start ?
in any case, thanks for your reply, i'll continue testing plain wine6 in the meantime.

**Comment by Gcenx** [comment]
Since the new MoltenVK will land at the end of the month I might just remove the Apple Silicon override as the next version fixes all the known issue that caused needing to force the older version.

Yes a lot of the CX20.0.x hacks gotten merged into upstream wine with improvements in some cases, wine-stable-6.0.1 includes the Apple Silicon required patches luckily my requests were accepted for that mostly.

I don’t think we’ll see much improvement with DXVK without the additional extensions getting implemented, however CX21 does have improvements within the WineD3D Vulkan backend. Not sure about about improvements for the DirectX9 and lower slowdowns some are trunking issues and others are M1 spwrcific

**Comment by Gcenx** [comment]
Didn’t mean to close sigh, I edited the comment with the remaining information.

**Comment by nsklaus** [comment]
good news, thanks for telling. also, i'll look forward the new molten at the end of the month.

i thought some of the issue i was having (cannot run fallout4 and such) might be because of wine-staging being in a transition state, and i should try wine-stable as well, however, i got this:

```
[ macports-wine ] 
$ sudo port uninstall wine-staging
Password:
--->  Deactivating wine-staging @6.11_0+ffmpeg
--->  Cleaning wine-staging
--->  Uninstalling wine-staging @6.11_0+ffmpeg
--->  Cleaning wine-staging
[ macports-wine ] 
$ sudo port install wine-stable   
--->  Computing dependencies for wine-stable
The following dependencies will be installed:  wine-mono-5.1.1
Continue? [Y/n]: 
Warning: No mirror sites on file for class /
--->  Fetching distfiles for wine-mono-5.1.1
--->  Attempting to fetch wine-mono-5.1.1-x86.tar.xz from https://distfiles.macports.org/wine-mono
--->  Attempting to fetch wine-mono-5.1.1-x86.tar.xz from https://github.com/madewokherd/wine-mono/releases/download/wine-mono-5.1.1/
--->  Verifying checksums for wine-mono-5.1.1                                        
--->  Extracting wine-mono-5.1.1
--->  Configuring wine-mono-5.1.1
--->  Building wine-mono-5.1.1
--->  Staging wine-mono-5.1.1 into destroot
Warning: wine-mono-5.1.1 installs files outside the common directory structure.
--->  Installing wine-mono-5.1.1 @5.1.1_0
--->  Activating wine-mono-5.1.1 @5.1.1_0
--->  Cleaning wine-mono-5.1.1
--->  Fetching distfiles for wine-stable
--->  Attempting to fetch wine-6.0.1.tar.gz from https://distfiles.macports.org/wine
--->  Attempting to fetch wine-6.0.1.tar.gz from https://github.com/wine-mirror/wine/archive/
--->  Verifying checksums for wine-stable                                                    
--->  Extracting wine-stable
--->  Applying patches to wine-stable
Error: Failed to patch wine-stable: command execution failed
Error: See /opt/local/var/macports/logs/_Users_klaus_Sources_macports-wine_x11_wine-stable/wine-stable/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port wine-stable failed
[ macports-wine ] 
$ 
```
here's the log file below. it seems some patchs failled to get applied.
[main.log](https://github.com/Gcenx/macports-wine/files/6688201/main.log)

**Comment by Gcenx** [comment]
Ah the patch format is git where the others aren’t guess I’d only did a commit for my personal copy, I’ll deal with that tonight.

**Comment by Gcenx** [comment]
Removed the CX-MoltenVK override used under Rosetta2 (won’t be needed soon anyway) and wine-stable-6.0.1 patches were made into git format matching wine-devel & wine-staging Ports.
