### ISSUE TITLE
Current known issues

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/macports-wine#19]
### macports-ports issues
- `curl` fails to compile for +universal (i386 & x86_64)
- `git` fails to compile (requires gettext)
- gstreamer1 packages are too old, use [macports-gstreamer1](https://github.com/Gcenx/macports-gstreamer1/tree/wine-specific-codecs-only)
- `ld64` - `ld64-latest` only provides 450
- `cctools` - matches Xcode11.3.1 however even on Mojave this can end up installing an llvm port instead of fallback of +xcode
- `nettle` (requires gettext)

Any Port that previously required `gettext` will now be broken when building in a clean envirement due to https://github.com/macports/macports-ports/commit/fea008a043ad2b96fd1ee872d7b2152de8210614 as the libaries won't be found as those are now installed via `gettext-runtime`, I'm assuming this _should_ work as `gettext-runtime` is a requirement of `gettext` but possibly everything needs to be rev-bumped?

_Strangly `curl` compiles as +universal just fine when all of `gettext` and sub-ports are installed_

### Wine-7.0 issues
- ~~Unable to compile below 10.11 _see [bug 52216](https://bugs.winehq.org/show_bug.cgi?id=52216)_~~ _(resolved wine-7.0-rc5)_
- `winemac.drv` doesn’t work below 10.11? [bug 52354](https://bugs.winehq.org/show_bug.cgi?id=52354)
- ~~Audio issues _see [bug 52202](https://bugs.winehq.org/show_bug.cgi?id=52202)_ _(patches in pipemail)_~~ _(resolved wine-7.0-rc3)
- winex11 not working within a VM _(not opened a bug yet)_
- MacOSX10.10.SDK or greater is required even with `LegacySupport` _(Mac OSX 10.8/10.9)_

**Comment by Gcenx** [comment]
@mascguy I honestly don’t feel like opening multiple tickets for this but after the `gettext` split being merged a thing that requires the libraries/headers now fail to compile from source in a clean environment.

@gverm mentioned having this issue and I’ve also experienced this issue in both my Mojave and 10.9VM rebuilds as I require +universal builds due to wine.

**Comment by Gcenx** [comment]
Possible workaround for this overlay.

Adding `p5-locale-gettext` and adding `gettext-runtime` as a requirement resolved the issue locally so depending on the outcome of macports-ports that could suffice in the interim since that Port doesn’t seem to change often making it an idea confidante.

**Comment by mascguy** [comment]
The various Python ports were just updated to use `getttext-runtime`, so that's one less to worry about.

As for `p5-locale-gettext`, that may be tackled soon as well. Alternatively, we can submit a PR for it, to ensure the update is expedited.

**Comment by mascguy** [comment]
It looks like `p5-locale-gettext` has no maintainer, so no PR is necessary. Testing the update locally, and will commit soon. (Will also reference this issue in the commit.)

**Comment by Gcenx** [comment]
@mascguy thanks for updating that one now that most of the affected Ports are fixed in macports-ports I should have less of a hard time testing upstream wine on an actual 10.9 install to see if there regression is only a VM issue or not.

**Comment by Gcenx** [comment]
@mascguy actually remaining annoyance is macports-base still not being able to make use of the macOS Mojave headers package to allow i386 arch when installed.

I’d opened a PR 223 (originally 212) that was over a year ago now, so lightly needs to be rebased.

Basically as you know macOS Mojave is the last version of macOS to natively support i386 arch but Xcode10 SDK doesn’t include a i386 slice.

However Xcode Command Line Tools 10 for macOS Mojave actually provides a headers package that once installed makes the install root act as an SDK like prior versions of macOS. However it seems no senior Macports member really attempted to verify this even though it’s known (yes the headers package also installed the framework headers). The result gives i386 & x86_64 capable sysroot that almost matches macOS High Sierra in compatibility along with some Mojave only things.

One commercial company who makes use of this has been CodeWeavers who compile there wine(64/32on64) using this as you’ll notice on macOS Mojave “wine” menu bar respects dark mode, I’ve also being doing the same for for official Winehq WIP packages.

As that PR seems to have simply stalled out I’ve been forcing the 10.13.SDK for compiling the required libraries but still compiling when wine packages using macOS Mojave sysroot.

**Comment by mascguy** [comment]
> @mascguy actually remaining annoyance is macports-base still not being able to make use of the macOS Mojave headers package to allow i386 arch when installed.
> 
> Basically as you know macOS Mojave is the last version of macOS to natively support i386 arch but Xcode10 SDK doesn’t include a i386 slice.
> 
> However Xcode Command Line Tools 10 for macOS Mojave actually provides a headers package that once installed makes the install root act as an SDK like prior versions of macOS. The result gives i386 & x86_64 capable sysroot that almost matches macOS High Sierra in compatibility along with some Mojave only things.

Just curious: If the various macOS SDKs were published as formal ports - and that's something @ryandesign has been working on - would that help in this case? Or is the problem that some components are specifically provided by the Xcode CLT - outside of the SDK realm - which would also have to be provided as well?

**Comment by Gcenx** [comment]
> Just curious: If the various macOS SDKs were published as formal ports - and that's something @ryandesign has been working on - would that help in this case? Or is the problem that some components are specifically provided by Xcode CLT - outside of the SDK realm - which would have to be provided as well?

@mascguy not really the entire ideal to being able to make use of `macOS_SDK_headers_for_macOS_10.14.pkg` on macOS Mojave is to avoid needing `MacOSX10.13.SDK` and forcing the 10.13 deployment target as is currently required.

The custom SDK Port ryandesign was working on requires a manual step of providing the required version of Xcode then the relevant SDK would then be extracted this brings its own issues for older versions of mac OS X that are no longer able to connect most modern websites without a newer browser etc.

My SDK Portfile goes the gray route and directly grabs the SDKs from known good sources and only provides select SDK packages that won't flag rev-upgrade.

**Comment by kencu** [comment]
One problem is that certain things in MacPorts are labelled as being “worked on” for literally years, and defacto nobody else is allowed to touch them, so they can really stagnate very badly.

**Comment by Gcenx** [comment]
@mascguy just incase you comment here I have noticed Ryan _finally_ started to publish his `MacOSX.sdk` ports, however I’ll be keeping my own implementation around.

**Comment by Gcenx** [comment]
@kencu is there any legitimate reason for cctools to require LTO support, it’s that really just need for ld64?

I’m hoping to avoid needing to install an llvm port just for cctools on Mojave to avoid the known as bug.

**Comment by Gcenx** [comment]
Well I _think_ it’s an as bug from memory according to your notes, cctools in Xcode11 has a bug that produced broken 32Bit binaries. You’d patched this in macports cctools (also fixed in newer cctools)

So I’m planning to force ether Macports cctools or my own for Mojave and below to avoid this bug.

**Comment by Gcenx** [comment]
@kencu keep forgetting to click comment _sigh_

The `as` bug caused i386 binary headers to be screwed up somehow causing the embedded info.plist to be invalid when using Xcode11 shipped cctools. You’d fixed that with the cctools port and it’s also fixed in later versions.

Still not exactly sure how useful LTO is for cctools but libstuff does pull it in so technically every component of cctools uses LTO somehow.

Seems the mingw-binutils bump might need to get pulled in here, the MoltenVK is also the same but I guess that doesn’t really concern me as I grab GitHub actions generated archives from my fork.

**Comment by Gcenx** [comment]
Welp @kencu & @mascguy lets see if Ryan takes action for my latest PR modernizing and updating both `wine` & `wine-devel`

**Comment by Gcenx** [comment]
@kencu welp looks like the /opt/bootstrap workaround for curl isn't working..., maybe the new macports bump caused this?

Been trying to rebuild a 10.9 environment and macports fails to download anything from githut/gitlab, clean install into /opt/bootstrap that where curl is installed, then another install into /opt/local using the ---with-curlprefix=/opt/bootstrap still macports can't download.....

**Comment by Gcenx** [comment]
I’ll retry tonight with the new curl bump but the issue in the logs was it complaining about certs, yet shouldn’t Macports built against libcurl should be using the Macports curl certs…?

Hoping this works with the new bump.

**Comment by Gcenx** [comment]
Reinstalled OS X Mavericks now theres no issues downloading files using macports libcurl....
