### ISSUE TITLE
Any interest in an updated wine-crossover port?

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/macports-wine#30]
Simply wanted to gauge interest in an updated `wine-crossover` Portfile.

This would function on macOS High Sierra and later and include support for running 32Bit applications/games on macOS Catalina and later.

**Comment by andyoneal** [comment]
I'd use it. I could compile it myself using your other repo but a portfile would be so much nicer and less error prone.

**Comment by Gcenx** [comment]
Going to wait and see if anyone else is interested.

![Screen Shot 2022-10-23 at 5 48 11 PM](https://user-images.githubusercontent.com/38226388/197429030-ee739aa8-c40f-4d06-9604-6f6baf25555a.png)
@kencu any idea how to get the usual little progress thing back for manual steps?\
Manual steps are required to even build this correctly.

**Comment by bikeridercz** [comment]
Yes, I'm interested too, I noticed that wine32on64 is missing on latest release of Wine crossover :-(. Unfortunately there is still one 32-bit application on my side that I need to run on my mac (Sparx Enterprise architect). Thanks for your work.

**Comment by Gcenx** [comment]
> Yes, I'm interested too.

So that’s at least 3 people that have interest in this (assuming Ken would like this)

> I noticed that wine32on64 is missing on latest release of Wine crossover :-( 

That binary is no longer required 

Here’s a snippet from Brendan on this matter
> One piece of advice would be that unlike previous releases, 'wine64' should now be used for running both 32- and 64-bit EXEs (at least for Catalina and later).

<br>

> Unfortunately there is still one 32-bit application on my side that I need to run on my mac (Sparx Enterprise architect). Thanks for your work.

There shouldn’t be an issue simply use wine or wine64 binaries to launch the 32Bit windows binary, that prebuilt only working on macOS Catalina and later ether way.

<br>

The `wine` binary is actually a copy of `wine64` this was done for winetricks comparability

**Comment by bikeridercz** [comment]
> The `wine` binary is actually a copy of `wine64` this was done for winetricks compatibility.

If `wine` means `Wine\ Crossover.app/Contents/MacOS/wine` then it is not the same as `wine64` because running following command fails with mentioned error ...

```
/Applications/Wine\ Crossover.app/Contents/MacOS/wine notepad
2022-11-22 16:07:50.766 wine[24876:2998587] launch path not accessible
```

**Comment by Gcenx** [comment]
This would really be off topic for this issue as it pertains to gauging interest in an updated `wine-crossover` Portfile. (I should have really explained that at the start)

<br> 

> /Applications/Wine\ Crossover.app/Contents/MacOS/wine

That isn’t a regular “wine” binary it’s an app bundle launcher that I believe is also broken in this version due to the removal of `wine`

> /Applications/Wine\ Crossover.app/Contents/Resources/wine/bin/wine64 notepad

Yes that would work as it’s an actual “wine” binary.

<br>

> The `wine` binary is actually a copy of `wine64` this was done for winetricks compatibility.

This only really applies to the brew formula as that creates the symlinks on install and the currently unpunished wine-crossover Portfile that just duplicates 

wine64 > wine
wine64-preloader > wine-preloader

<br>

CrossOver-22.0.x and later upstream wine WoW64 system will use wine64 for everything.

**Comment by davidcorry** [comment]
I am interested as well.

**Comment by Gcenx** [comment]
According to Meredith CX22.1.0 will be seeing a release soon so I’ll hold off on committing the current version until those sources land

**Comment by Gcenx** [comment]
Not sure when CX22.1 will actually land so pushed https://github.com/Gcenx/macports-wine/commit/0e066b1872bb1408ea056880ab6153e012b781a3 for the new `wine-crossover`
