### ISSUE TITLE
python310 - build failure (Mojave 10.14.6) 

### ISSUE THREAD

**Issue by contextnerror** [Gcenx/macports-wine#37]
Python310 fails during the build stage, preventing wine-devel from being installed. MacOSX10.13.sdk port has been installed, .conf file has been changed per README. Logs for wine and python are attached.
[wine-main.log](https://github.com/Gcenx/macports-wine/files/10094765/wine-main.log)
[python-main.log](https://github.com/Gcenx/macports-wine/files/10094766/python-main.log)

**Comment by Gcenx** [comment]
I’ve looked over the relevant log `python-main.log` and it seems the issue might be related to having installed Xcode Command Line tools 11.

I have Xcode Command Line Tools 10 installed on my own macOS Mojave install

Once I’m home I’ll pull `python310` into the overlay within a PR and add the muniversal portgroup that might help resolved this one from the looks of it.

**Comment by Gcenx** [comment]
I’ve not had time to test if using the muniversal portgroup helps or not but I’d recommend removing Xcode11 command line tools and instead installing Xcode 10 command line tools and ensure to Xcode select it.

**Comment by Gcenx** [comment]
If you’ve installed Xcode10 Command Line Tools you’ll need to deactivate MacOSX10.13.SDK and install it again so the required symlink gets fixed

Probably need to run clean on gstreamer1 along with wine-devel so it doesn’t get confused.

**Comment by Gcenx** [comment]
macOS Mojave [gstreamer1+universal_main.log](https://github.com/Gcenx/macports-wine/files/10141798/main.log)

I have no issue building `gstreamer1` as +universal on my macOS Mojave drive.

**Comment by Gcenx** [comment]
Looks like I missed that error, fixed.

Still theres no need to manually run `portindex` once if you've setup this overlay as explained that will be generated automatically and updated when you run `port selfupdate`

**Comment by Gcenx** [comment]
Should be fixed with https://github.com/Gcenx/macports-wine/commit/4036d93afa82c251f77fdfad2209b0a821941750 

Seems pkgconfig isn't finding anything for i386 only x86_64 no idea why.

**Comment by Gcenx** [comment]
An issue only on the i386 slice and it looks like gstreamer.

I’ve not ran a full build on my macOS Mojave system since the gstreamer update, I’m currently testing a possible fix.

**Comment by Gcenx** [comment]
No issues on my end so it should have been resolved via https://github.com/Gcenx/macports-wine/commit/adfe53a7c1e11ea31f84031b81412cea27ca21e8

**Comment by Gcenx** [comment]
> Thank you very much, it's installed working now.

Glad it’s now working for you.

> Do I still need to keep the `deployment_target` and `sdk_version` in my .conf file?

Yes those are required to enable i386 support on macOS Mojave.
