### ISSUE TITLE
Please review the updated Portfile

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/macports-wine#4]
@kencu here is the updated Portfile, I know the max version would need to be changed to 10.13 if it's to be accepted but I'm not sure if I handled mingw-w64 correctly as it was previously freaking out due to the usage of +universal

**Comment by kencu** [comment]
Hmm yes -- I'm not too familiar with the mingw* business, but the messages are a bit intimidating:
```
$ sudo port -v install +universal
--->  Computing dependencies for wine-devel...........
Error: Cannot install i686-w64-mingw32-crt for the archs 'i386 x86_64' because
Error: its dependency i686-w64-mingw32-gcc-bootstrap does not build for the required archs by default
Error: and does not have a universal variant.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port wine-devel failed
```
ok -- try
```
$ sudo port -v install mingw-w64 -universal
--->  Computing dependencies for mingw-w64..................
The following dependencies will be installed: 
 i686-w64-mingw32-binutils
 i686-w64-mingw32-crt
 i686-w64-mingw32-gcc
 i686-w64-mingw32-gcc-bootstrap
 i686-w64-mingw32-gcc-nothreads
 i686-w64-mingw32-headers
 i686-w64-mingw32-winpthreads
 isl
 libmpc
 mpfr
 x86_64-w64-mingw32-binutils
 x86_64-w64-mingw32-crt
 x86_64-w64-mingw32-gcc
 x86_64-w64-mingw32-gcc-bootstrap
 x86_64-w64-mingw32-gcc-nothreads
 x86_64-w64-mingw32-headers
 x86_64-w64-mingw32-winpthreads
Continue? [Y/n]: n
```
OK, how about
```
$ port info i686-w64-mingw32-gcc-bootstrap
i686-w64-mingw32-gcc-bootstrap @9.1.0 (cross, devel)

Description:          The GNU compiler collection, including front ends for C, C++, Objective-C
                      and Objective-C++ for cross development for i686-w64-mingw32.
Homepage:             https://gcc.gnu.org/

Extract Dependencies: xz
Build Dependencies:   gettext
Library Dependencies: i686-w64-mingw32-binutils, gmp, mpfr, isl, libiconv, libmpc, zlib,
                      i686-w64-mingw32-headers
```

At this moment, I'm not totally sure exactly which way to go here for a clean installation. Can you give me a clue?

**Comment by kencu** [comment]
I installed libquicktime-devel as it appeared to be wanting that.
Then I installed isl, libmpc, and mpfr all +universal. Those could all be depped separately I guess.

And then I just sorta went for it:
```
$ sudo port -v install mingw-w64 -universal
--->  Computing dependencies for mingw-w64...............
The following dependencies will be installed: 
 i686-w64-mingw32-binutils
 i686-w64-mingw32-crt
 i686-w64-mingw32-gcc
 i686-w64-mingw32-gcc-bootstrap
 i686-w64-mingw32-gcc-nothreads
 i686-w64-mingw32-headers
 i686-w64-mingw32-winpthreads
 x86_64-w64-mingw32-binutils
 x86_64-w64-mingw32-crt
 x86_64-w64-mingw32-gcc
 x86_64-w64-mingw32-gcc-bootstrap
 x86_64-w64-mingw32-gcc-nothreads
 x86_64-w64-mingw32-headers
 x86_64-w64-mingw32-winpthreads
```
And we'll see what kind of a state I'm in at the end of it all :>

**Comment by Gcenx** [comment]
The i686 is 32Bit and the x86_64 is of course 64Bit, the thing I don’t believe mingw-w64 should even acknowledge the +universal flag since it’s a complete toolchain for cross-compiling.

I would need a way to install mingw-w64 without having +universal or anything else passed into it.

I tested by installing wine-devel first then installing wine-devel got it functioning.

**Comment by Gcenx** [comment]
As for QuickTime you technically don’t need it officially QuickTime.framework was depreciated after the 10.11SDK and Apple only officially provided 32Bit support.

I’m not sure if wine detects libquicktime-devel I’ve never tried

**Comment by kencu** [comment]
**It works!** 

Thanks!

Beautiful, thank you very much! Fonts look much better than the old "wine" port in MacPorts. I have to learn more about how to make "wine" do it's tricks. I usually just go over to my PC, or to Parallels...but wine looks quite excellent.

I noticed that wine ignored  libquicktime-devel even though I had it installed, so either it's not used or I misconfigured it somehow.

**Comment by kencu** [comment]
@ryandesign -- I installed this right-up-to-date version of wine-devel just a while ago, and it seems solid enough to mention that you might be interested in taking a look / collaborating with this interested user about it. I know you have a lot on your plate other than wine, and he's interested....

Also, we seem to have the universal-on-mojave thing working quite well, and although it will likely never be of general interest or use (ie who but geeks like us are going to set up a full separate macports prefix for +universal? Well, maybe there are some people .. it might possibly be of use to you.

**Comment by Gcenx** [comment]
@kencu yeah the way wine supports QuickTime is via the QuickTime.framework that’s now depreciated after the 10.11SDK it was 32Bit anyway. _(You could manually copy it from the 10.11 or lower SDK and place into macports Frameworks folder to make wine32 happy)_

The **blocker** for this would be `mingw-w64` freaking over +universal as _mingw-w64_ is required since wine-4.15, compiling without causes breakages.

I’ll get `wine`and `wine-crossover` updated also those don’t need mingw-w64 for now so no real blockers for those, but to fix the fonts it’s ether adding an export variable to force freetype to use the older render mode or rebasing the patch used to support the newer freetype versions rendering mode.

I would have liked to enable _MoltenVK_ but last I checked the Port was using an ancient version, the current prebuilt MoltenVK SDK is usable with the 10.11SDK and  above _(10.15+ would be better using the newer Metal 3.0 version)_
