### ISSUE TITLE
Wine can't load MoltenVK

### ISSUE THREAD

**Issue by gasinvein** [Gcenx/macports-wine#46]
Trying to run a x64 `vkcube.exe` with Wine on a M1 mac gives this error window:
<img width="385" alt="wine_moltenvk_error" src="https://user-images.githubusercontent.com/4569691/208468062-80dc36a7-492a-4f1d-8c78-b21cee028b94.png">
while wine prints the following errors:
```
0024:err:vulkan:wine_vk_init Failed to load libMoltenVK.dylib
0024:err:vulkan:init_vulkan Failed to load Wine graphics driver supporting Vulkan.
```
However, with MoltenVK installed from the main MacPorts repo, `vkcube.exe` does work.

**Comment by Gcenx** [comment]
Ah yes I didn’t get chance to fix the MoltenVK Portfile, what’s happening is it’s only being installed for arm64.

**Comment by gasinvein** [comment]
Hmm, given the MoltenVK port from the main repo seems to work fine, why do you need a custom one at all?

**Comment by Gcenx** [comment]
I’ve committed some changes in #47 this hasn’t been tested yet as I’m at work.

**Comment by Gcenx** [comment]
The wine ports and MoltenVK have now been fixed, I didn’t rev bump MoltenVK however.

**Comment by gasinvein** [comment]
Thanks!
