### ISSUE TITLE
Fails to install wine-devel

### ISSUE THREAD

**Issue by MichaelGDev48** [Gcenx/macports-wine#67]
Error: Checksum (rmd160) mismatch for wine-8.0.tar.gz
Error: Checksum (sha256) mismatch for wine-8.0.tar.gz
Error: Checksum (size) mismatch for wine-8.0.tar.gz
Error: Failed to checksum wine-devel: Unable to verify file checksums
[main.log](https://github.com/Gcenx/macports-wine/files/10543477/main.log)

**Comment by MichaelGDev48** [comment]
i just did a git pull and it didnt change anything btw

**Comment by Gcenx** [comment]
Here what I'm getting [main.log](https://github.com/Gcenx/macports-wine/files/10547066/main.log)

I'd removed the distfile then let the portifle download it over, the checksum matches so not sure what happened on your end.

**Comment by MichaelGDev48** [comment]
Now I am getting this error
```
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_macports-wine_emulators_wine-devel/wine-devel/work/wine-wine-8.0" && /usr/bin/make -j8 -w all 
:info:build Exit code: 2
:error:build Failed to build wine-devel: command execution failed
:debug:build Error code: CHILDSTATUS 86881 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec -callback portprogress::target_progress_callback build"
:debug:build     (procedure "portbuild::build_main" line 8)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_opt_macports-wine_emulators_wine-devel/wine-devel/main.log for details.
```

**Comment by Gcenx** [comment]
Please attach the main.log as the provided output isn’t helpful

**Comment by MichaelGDev48** [comment]
[main.log](https://github.com/Gcenx/macports-wine/files/10552156/main.log)

**Comment by Gcenx** [comment]
That was annoying to track-down the problem my usage of `configure.pre_args.x86_64` caused `muniversal-1.1.tcl` to _not_ inject `--host` & `--build` these are both required to build wine correctly from arm.

I've pushed a commit that seems to have resolved the issue on my Apple Silicon system.

**Comment by Gcenx** [comment]
The issues you’d seen with the archive checksum not matching might have been caused by https://github.com/orgs/community/discussions/45830
