### ISSUE TITLE
10.9 Mavericks - cannot build cctools

### ISSUE THREAD

**Issue by MrLeRien** [Gcenx/macports-wine#88]
hello!
I've been trying to install wine-stable using 10.9.5 Mavericks, but ran into a problem building the cctools dependency.
i didn't install any port package beforehand and just built macports from source, added/synced your repo and ran `port -v install wine-stable` as root.
[main.log](https://github.com/Gcenx/macports-wine/files/12238871/main.log)

**Comment by Gcenx** [comment]
Restore a removed patch in https://github.com/Gcenx/macports-wine/commit/aea23d4300ea05f342b55e2a1ff5087362956328 let me know if that fixes `cctools` for you.

**Comment by MrLeRien** [comment]
thanks for your speedy response, unfortunately the build still failed for me :/
[main.log](https://github.com/Gcenx/macports-wine/files/12239980/main.log)

**Comment by Gcenx** [comment]
_Sigh_ I'll convert my `cctools` port to a versioned copy when I'm free so you'll default to macports-ports version.

For now you could add a local overlay that's above macports-wine and add macports-ports cctools that will get you going again, _ would highly recommend skipping gstreamer support for wine.

> port install wine-stable -gstreamer

**Comment by Gcenx** [comment]
This should now be resolved via https://github.com/Gcenx/macports-wine/commit/816a1eda1257c33076772a550c8a268c33223791 & https://github.com/Gcenx/macports-wine/commit/f49171b480ed750d6d316b204a28b156240fc24b

**Comment by MrLeRien** [comment]
can confirm cctools now installs successfully.

i'll try building wine-stable without gstreamer as you recommended and i'll get back to you if it fails.
thanks alot!
