### ISSUE TITLE
gl-headers and game-porting-toolkit unavailable in the repositories

### ISSUE THREAD

**Issue by mazeltovelss** [Gcenx/macports-wine#97]
Hi,

I'm trying to rebuild wine on my MBP running Mojave 10.14.6 using macports, as I accidentally updated my homebrew build last month and lost some graphical API support to run Diablo 2 on the machine. I've built the macports-wine repository locally and have successfully installed the listed ports, except for gl-headers and game-porting-toolkit. The gl-headers tarball is not fetchable at its listed repositories, and game-porting-toolkit is simply not found.

I've tried to install wine-devel, wine-stable, and wine-crossover, as their current listed versions (v8.21, v8.0.2, and v22.1.1) all depend gl-headers, hoping to hit a repository address, but they all fail. I cannot find much info about the gl-headers elsewhere and if I'm missing something about the install please let me know.  Thanks

**Comment by mazeltovelss** [comment]
The `-gstreamer` command solved the compile and install issue. I'll go down the bootstrap route if I ever need this machine to go there. `winecfg` booted up no problem, and I'll need to make a few more tweaks to test out the graphical APIs. Thanks for the quick help!

**Comment by nmlynch94** [comment]
For anyone in the future, I worked around this by downloading the headers from https://gitlab.freedesktop.org/gstreamer/meson-ports/gl-headers/-/archive/5c8c7c0d/gl-headers-5c8c7c0d.tar.bz2 with wget manually and placed it in /opt/local/var/macports/distfiles. This made it recognize the file from the cache and skip trying to download it. I'm on Mojave.
